---
abstract: 'mirror parts of your app e.g. for offline hacking'
author:
  - 'Shawn M Moore <code@sartak.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-ActiveMirror
requires:
  CHI: 0
  JSON: 0
  Web::Request: 0
version: 0.01
